data:
  data_root: 'data/samples/training/*.nc'
  data_source: 'cds'
  target_vars: ['tcc']
  time_column: 'time'
  save_dir: ''

training:
  max_encoder_length: 365
  min_encoder_length: 182
  max_prediction_length: 365
  min_prediction_length: 12
  batch_size: 64
  num_workers: 8
  max_epochs: 100
  gradient_clip_val: 0.1
  limit_train_batches: 100
  log_every_n_steps: 10
  early_stop_patience: 10
  early_stop_min_delta: 0.00001
  reduce_on_plateau_patience: 4
  learning_rate: 0.01
  hidden_size: 64
  attention_head_size: 4
  dropout: 0.1
  ouptut_size: 7
  hidden_continuous_size: 64

hyperparameter_tuning:
  enable: False
  n_trials: 100
  learning_rate_range: [0.001, 0.1]
  hidden_size_range: [8, 128]
  attention_head_size_range: [1, 4]
  dropout_range: [0.1, 0.3]
  hidden_continuous_size_range: [8, 128]
  gradient_clip_val_range: [0.01, 1.0]
  limit_train_batches: 30
  early_stop_patience: 10
  early_stop_min_delta: 0.00001
  reduce_on_plateau_patience: 4
  log_every_n_steps: 10
  max_epochs: 50

evaluation:
  eval_data_root: 'data/samples/testing/*.nc'
  model_path: ''
  eval_save_dir: ''

logging:
  base_dir: './results'
  training_subdir: 'trainings'
  evaluation_subdir: 'evaluations'
  checkpoint_subdir: 'checkpoints'
  log_subdir: 'logs'
  inference_subdir: 'inferences'

checkpoint:
  checkpoint_filename: 'checkpoint_{epoch:03d}_{val_loss:.4f}'
  best_model_filename: 'best_model.ckpt'
  monitor: 'val_loss'
  mode: 'min'
  save_top_k: -1
  every_n_epochs: 5
  save_last: True
  save_weights_only: False
  verbose: False