data:
  data_root: 'data/samples/training/*.nc'
  data_source: 'cds'
  target_vars: ['tcc', 'hcc', 'mcc', 'lcc', 'tciw', 'tclw']
  time_column: 'time'
  save_dir: ''

training:
  max_encoder_length: 365
  min_encoder_length: 182
  max_prediction_length: 365
  min_prediction_length: 12
  batch_size: 16
  num_workers: 4
  max_epochs: 50
  gradient_clip_val: 0.1
  limit_train_batches: 30
  log_every_n_steps: 10
  early_stop_patience: 10
  early_stop_min_delta: 0.0001
  reduce_on_plateau_patience: 4
  learning_rate: 0.01
  hidden_size: 32
  attention_head_size: 2
  dropout: 0.1
  hidden_continuous_size: 32

hyperparameter_tuning:
  enable: true
  n_trials: 100
  learning_rate_range: [0.001, 0.1]
  hidden_size_range: [8, 128]
  attention_head_size_range: [1, 4]
  dropout_range: [0.1, 0.3]
  hidden_continuous_size_range: [8, 128]
  gradient_clip_val_range: [0.01, 1.0]
  limit_train_batches: 30
  early_stop_patience: 10
  early_stop_min_delta: 0.0001
  reduce_on_plateau_patience: 4
  log_every_n_steps: 10
  max_epochs: 50

evaluation:
  eval_data_root: 'data/samples/testing/*.nc'
  eval_save_dir: ''

checkpoints:
  base_dir: './models'
  training_dir: 'trainings'
  evaluation_dir: 'evaluations'
  checkpoint_filename: 'checkpoint_{epoch:02d}'
  best_model_filename: 'best_model.ckpt'